name: deploy-site

on:
  push:
    branches:
      - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,nodefaults
          channel-priority: strict
          activate-environment: raijin
          auto-update-conda: false
          python-version: 3.9
          environment-file: ci/environment.yml
          use-only-tar-bz2: true

      - name: Build
        run: |
          conda env list
          cd raijin
          make -j4 html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./raijin/_build/html
          cname: raijin.ucar.edu
